version: '2'
services:
  proxy:
    build:
      context: ./envoy
      dockerfile: Dockerfile.proxy
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml
      - ./target/wasm32-unknown-unknown/debug/envoy_wasm_filter.wasm:/etc/envoy_wasm_filter.wasm
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "80:18000"
      - "8001:18001"

  web_service:
    image: mendhak/http-https-echo
    networks:
      envoymesh:
        aliases:
          - web_service
    expose:
      - "8080"
    ports:
      - "8080:80"
  
  grpc_service:
    image: tkpd/gripmock:v1.10
    ports:
      - "4770:4770"
      - "4771:4771"
    volumes:
      - "./proto:/proto"
      - "./stubs:/stubs"
    command: 
      - '--stub=/stubs'
      - '/proto/file1.proto'
    networks:
      envoymesh:
        aliases:
          - grpc_service


networks:
  envoymesh: {}
