apiVersion: v1
kind: Namespace
metadata:
  name: echo-app
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo-app
  name: echo-app
  namespace: echo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
      - image: mendhak/http-https-echo
        name: echo
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo-app
  name: echo-app
  namespace: echo-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: echo-app
  type: ClusterIP
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: echo-envoy-wasm-filter
  namespace: echo-app
spec:
  selector:
    matchLabels:
      app: echo-app
  url: oci://registry.kube-system.svc.cluster.local/envoy-wasm-plugin:latest
  pluginConfig:
    header_1: "some_value_1"
    header_2: "another_value"
